Update test

diff --git a/.github/workflows/ci-label.yml b/.github/workflows/ci-label.yml
--- a/.github/workflows/ci-label.yml
+++ b/.github/workflows/ci-label.yml
@@ -25,24 +25,32 @@ jobs:
       - name: Get Pull Request Number
         id: get_pr
         run: |
-         PR_NUMBER=$(jq -r '.workflow_run.pull_requests[0].number' < $GITHUB_EVENT_PATH)
-         if [ -z "$PR_NUMBER" ]; then
-            echo "Pull Request number could not be determined. Exiting."
-            exit 1
-         fi
-         echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+          PR_NUMBER=$(jq -r '.workflow_run.pull_requests[0].number' < $GITHUB_EVENT_PATH)
+          BRANCH_NAME=$(jq -r '.workflow_run.head_branch' < $GITHUB_EVENT_PATH)
+
+          if [ -z "$PR_NUMBER" ] || [ -z "$BRANCH_NAME" ]; then
+            echo "Pull Request number or branch could not be determined. Exiting."
+          exit 1
+          fi
+
+          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
+
 
       - name: Check Status of All Workflows
         run: |
           pr_number=${{ env.PR_NUMBER }}
-          echo "Checking statuses for PR #$pr_number"
+          branch_name=${{ env.BRANCH_NAME }}
+          echo "Checking statuses for PR #$pr_number on branch $branch_name"
 
           workflows=("KFP Manifests")
-
           all_success=true
+
           for workflow in "${workflows[@]}"; do
             echo "Checking status for workflow: $workflow"
-            statuses=$(gh run list --workflow "$workflow" --pr $pr_number --json status -q '.[] | .status')
+
+            # Check the status of the workflow for the given branch
+            statuses=$(gh run list --workflow "$workflow" --branch "$branch_name" --json status -q '.[] | .status')
 
             # Check if any status is not 'success' (including failed or skipped)
             if echo "$statuses" | grep -qv "success"; then
